graph LR
    A[Guest] --> B[Sign in]
    A --> C[Sign up]
    B --> D[User]
    C --> D
    D --> E[Create lot and room autocreates for this lot]
    D --> F[Enter the room with lot]
    F --> G[Performing bids on lots]
    D --> K[View bid statistics]